# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  #imports =
  #[ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  boot.initrd.luks.devices = {
    root = {
      device = "/dev/nvme0n1p2";
      preLVM = true;
      allowDiscards = true;
    };
  };

  hardware.enableAllFirmware = true;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a182a6c4-bce6-4ed1-b1db-3bc08ede9ae5";
    fsType = "ext4";
    options = ["noatime" "nodiratime" "discard"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3A59-DF18";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6d3dd75b-b673-4d79-82fe-3a10b5d39d18";
    fsType = "ext4";
    options = ["noatime" "nodiratime" "discard"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/c992a20b-af62-402c-a9c6-58335830aada";}
  ];

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
