#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Set wallpaper
swaybg --output '*' --mode fill --image ~/.config/wallpapers/default_wallpaper &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start graphical session target services
systemctl --user start graphical-session.target

# Start mpd
exec mpd &
